function conf = loadPlatformConfig( fname , params )
% LOADPLATFORMCONFIG loads the platform configuration data from a script
%
% Evaluates the script passed as fname and returns the structure c defined
% by the script.
%
%   Examples:
%
%      conf = loadConfig( fname, params );
%
 
 eval(fname);
 
 if(~exist('c','var'))
     error('bad syntax in the configuation file %s',fname);
 else 
    conf = c;
    % cleanup the structure generated by the configuration file
    clear c;
 end
end

